### ISSUE TITLE
Not returned five hundredth error

### ISSUE THREAD

**Issue by tuwilof** [GateprotectGmbH/sparrow#15]
Hello, thank you for your cool gem. But when you use the gem and attempts to return a status such as 507, the application falls
```
[2015-11-09 12:31:16] ERROR NoMethodError: undefined method `each' for "":String
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:112:in `service'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/home/dima/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by anmuel** [comment]
hi tuwilof, thanks for your contribution :)

I'm digging into this.

As per default configuration 500-511 status codes should simply be passed, so let's see where the real bug hides.

**Comment by tuwilof** [comment]
Thank you, after update gem to 0.0.14 it working correctly
